spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ss_prod
    username: ss_prod_user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false